# -*- coding: utf-8 -*-
"""MAPLE-Testing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X59bzLNU0gLwVydTQhOApzYsAFKRTdvV
"""

# Remember to git clone https://github.com/GDPlumb/MAPLE.git into same directory as this script

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import json
import re
import ast
import sys
from MAPLE.Code import MAPLE
import numpy as np

def process_spectra(file_obj, file_name):
    file_string = str(file_obj[file_name])

    return file_string.split("\\n")

def process_matrix(file_obj, file_name):
    file_string = str(file_obj[file_name])

    result = file_string.split("\\n")
    result[0] = result[0].replace("b'", "")

    for i in range(len(result)):
        result[i] = result[i].split(" ")
        result[i] = [int(x) if x.isdigit() else x for x in result[i]]
        lastel = result[i][-1]
        if lastel == "+":
            result[i][-1] = 1
        elif lastel == "-":
            result[i][-1] = 0
    
    return result

def write_output_file(filename, obj, is_reverse=False):
    with open(filename, 'w') as file:
        sorted_dict = sorted(obj.items(), key=lambda x: x[1], reverse=is_reverse)
        for i in sorted_dict:
            file.write(";".join([i[0], str(i[1])]) + "\n")

#Input and process files into dataframe
#Input: File paths, both spectra and matrix. System finds the files
#Output: Dataframe (Spectra List + PASS/FAIL labels as column and Test instances as rows with its execution matrix)

f = open(sys.argv[1], "r")
spectra_list = [line.rstrip('\n') for line in f]
spectra_list.append("Pass/Fail")
f.close()

#Case if there are duplicate in list
seen = {}
for i, x in enumerate(spectra_list):
    if x not in seen:
        seen[x] = 1
    else:
        seen[x] += 1
        num = seen[x]
        temp = x.split('#')
        temp_name = temp[0] + str(num)+ '#' + temp[1]
        spectra_list[i] = temp_name 


df = pd.read_csv(sys.argv[2], sep=' ', names=spectra_list, header=None)
df = df.replace(["-","+"], [0,1])

#Split dataframe into variables and classes as well as handle any insufficient data 
#(Handles insufficient number labelled instance by appending a copy of that instance; Handles insufficient total number of instance by reappending the dataframe)
#Input: Dataframe created from spectra and matrix files
#Output: Dataset for model training and model testing (e.g., x_train -> instance feature values for training, y_test -> instance label for training)

x = df[spectra_list[:len(spectra_list)-1]]
y = df["Pass/Fail"]

fails = []
passes = []
i = 0
for result in y:
    if result == 0:
        fails.append(i)
    else:
        passes.append(i)
    i += 1

if len(fails) == 1:
    df = df.append(df.iloc[fails[0]])
    x = df[spectra_list[:len(spectra_list)-1]]
    y = df["Pass/Fail"]

if (df.shape[0] < 6):
    df = df.append(df)
    x = df[spectra_list[:len(spectra_list)-1]]
    y = df["Pass/Fail"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, stratify=y, random_state=1)

#Declare and train the model (Current model is Random Forest)
#Input: Training dataset (x_train, y_train)
#Output: Trained model

model = RandomForestClassifier(n_estimators=100, bootstrap=True, max_features='sqrt', random_state=1)

model.fit(x_train, y_train)

#Declare MAPLE explainer object
#Input: Trained model predict function & trained dataset (x_test), test dataset (x_test), prediction array from model x_test in a form NumPy array
#Output: Explainer object (MAPLE Method)

exp = MAPLE.MAPLE(np.array(x_train), np.array(model.predict(x_train)), np.array(x_test), np.array(model.predict(x_test)))

#Explain each feature's contribution based on its coefficient
#Input: Explanation object and array of "FAIL"-labelled instances
#Output: Dictionary of the contribution (represented by coefficient) of each feature when a prediction is made on a failed instance 

feature_coefficients_based_on_error_instance = {}

for i in fails:
    cur_coefs = list(exp.explain(np.array(x.iloc[i]))['coefs'])
    feature_coefficients_based_on_error_instance[i] = []
    for index, val in enumerate(cur_coefs[:-1]):
        test_string = spectra_list[index] + ";" + str(val)
        feature_coefficients_based_on_error_instance[i].append(test_string)

#Process individual coefficient along with mean, min, and max values
#Input: Dictionary of the contribution (represented by coefficient) of each feature when a prediction is made on a failed instance
#Output: Dictionaries of each line of code's coefficient results, max, mean, min coefficient values

coef_values_on_predict = {}

for i in feature_coefficients_based_on_error_instance:
    for j in feature_coefficients_based_on_error_instance[i]:
        feature_and_value = j.split(";")
        value = float(feature_and_value[1])
        feature = feature_and_value[0]
        if feature not in coef_values_on_predict:
            coef_values_on_predict[feature] = []
        coef_values_on_predict[feature].append(value)

feature_coef_means = {}
feature_coef_max = {}
feature_coef_min = {}

for i in coef_values_on_predict:
    feature_coef_means[i] = sum(coef_values_on_predict[i]) / len(coef_values_on_predict[i])
    feature_coef_max[i] = max(coef_values_on_predict[i])
    feature_coef_min[i] = min(coef_values_on_predict[i])

#Write output file
#Input: Dictionaries of each line of code's coefficient results, max, mean, min coefficient values
#Output: .txt Files containing each line of code's coefficient values, mean, max, and min coefficient values

with open(sys.argv[3] + "_maple_results.txt", "w") as file:
    for i in feature_coefficients_based_on_error_instance:
        file.write(str(i) + "\n")
        for j in range(len(feature_coefficients_based_on_error_instance[i])):
            file.write(feature_coefficients_based_on_error_instance[i][j] + "\n")

write_output_file(sys.argv[3] + '_maple_mean.txt', feature_coef_means)
write_output_file(sys.argv[3] + '_maple_max.txt', feature_coef_max)
write_output_file(sys.argv[3] + '_maple_min.txt', feature_coef_min)

