# -*- coding: utf-8 -*-
"""Dalex-testing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aBwjZCdfe2MbPzFRY9TjRfbSFJq2htbU
"""

#Be sure to install the dalex package using pip

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from google.colab import files
import pandas as pd
import json
import re
import ast
import dalex
import numpy as np

def process_spectra(file_obj, file_name):
    file_string = str(file_obj[file_name])

    return file_string.split("\\n")

def process_matrix(file_obj, file_name):
    file_string = str(file_obj[file_name])

    result = file_string.split("\\n")
    result[0] = result[0].replace("b'", "")

    for i in range(len(result)):
        result[i] = result[i].split(" ")
        result[i] = [int(x) if x.isdigit() else x for x in result[i]]
        lastel = result[i][-1]
        if lastel == "+":
            result[i][-1] = "PASS"
        elif lastel == "-":
            result[i][-1] = "FAIL"
    
    return result

#Input and process files into dataframe

spectra_file = files.upload()
matrix_file = files.upload()

spectra_list = process_spectra(spectra_file, list(spectra_file.keys())[0])
spectra_list[-1] = "Pass/Fail"
spectra_list[0] = spectra_list[0].replace("b'", "")

matrix_list = process_matrix(matrix_file, list(matrix_file.keys())[0])

matrix_list.pop()

df = pd.DataFrame(data=matrix_list, columns=spectra_list)

#Split dataframe into variables and classes as well as handle any insufficient data

x = df[spectra_list[:len(spectra_list)-1]]
y = df["Pass/Fail"]

fails = []
passes = []
i = 0
for result in y:
    if result == "FAIL":
        fails.append(i)
    else:
        passes.append(i)
    i += 1

if len(fails) == 1:
    df = df.append(df.iloc[fails[0]])
    x = df[spectra_list[:len(spectra_list)-1]]
    y = df["Pass/Fail"]

if (df.shape[0] < 6):
    df = df.append(df)
    x = df[spectra_list[:len(spectra_list)-1]]
    y = df["Pass/Fail"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, stratify=y, random_state=1)

#Declare and train the model

model = RandomForestClassifier(n_estimators=100, bootstrap=True, max_features='sqrt', random_state=1)

model.fit(x_train, y_train)

#Declare DALEX explainer object

exp_dalex = dalex.Explainer(model, data=x_train, y=y_train, model_type="classification")

#Explain variable's contribution using Dalex breakdown plot approach

breakdown_fail = exp_dalex.predict_parts(x.iloc[18], type="break_down")
breakdown_fail_interaction = exp_dalex.predict_parts(x.iloc[18], type="break_down_interactions")

dalex_lines = {}

for index, row in breakdown_fail.result.iterrows():
    if index == 0 or index == len(breakdown_fail.result) - 1:
        continue
    dalex_lines[row['variable_name']] = row['contribution']

#Write output file

with open("Math-8-dalex.txt", "w") as file:
    for i in dalex_lines:
        file.write(str(i) + ";" + str(dalex_lines[i]) + "\n")
